### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array. VContainer.Internal.CappedArrayPool

### ISSUE THREAD

**Issue by dre0dru** [hadashiA/VContainer#60] opened 2020-11-22 22:23 UTC
Hello! I am trying to register class that has inheritance chain from several generic classes, like:
```
public ISomeInterface<T>{

}

public abstract class Base<T>: ISomeInterface<T>{

}

public abstract class AnotherBase<T>: Base<T>{
   private readonly SomeDependency _dep;

   protected AnotherBase(SomeDependency dep){
      _dep = dep;
   }
}

public class ActualClass: AnotherBase<ActualGenericClass>
{
   public ActualClass(SomeDependency dep): base(dep){
   }
}
```
`SomeDependency` is a `ScriptableObject` that is registered like this with `builder.RegisterInstance(_dep);`.
The next line is `builder.Register<ActualClass>(Lifetime.Singleton);`

And that gives me that error on container resolve:
```
IndexOutOfRangeException: Index was outside the bounds of the array.
VContainer.Internal.CappedArrayPool`1[T].Rent (System.Int32 length) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/CappedArrayPool.cs:51)
VContainer.Internal.ReflectionInjector.CreateInstance (VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:31)
VContainer.Internal.Registration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:44)
VContainer.Container+<>c__DisplayClass4_0.<.ctor>b__1 () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:132)
System.Lazy`1[T].CreateValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].LazyInitValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].get_Value () (at <9577ac7a62ef43179789031239ba8798>:0)
VContainer.Container.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:152)
VContainer.Container.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:140)
VContainer.IObjectResolverExtensions.ResolveOrParameter (VContainer.IObjectResolver resolver, System.Type parameterType, System.String parameterName, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/IObjectResolverExtensions.cs:30)
VContainer.Internal.ReflectionInjector.CreateInstance (VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:39)
VContainer.Internal.Registration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:44)
VContainer.Container.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:150)
VContainer.Internal.CollectionRegistration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:92)
VContainer.Container.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:150)
VContainer.Container.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:140)
VContainer.IObjectResolverExtensions.ResolveOrParameter (VContainer.IObjectResolver resolver, System.Type parameterType, System.String parameterName, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/IObjectResolverExtensions.cs:30)
VContainer.Internal.ReflectionInjector.CreateInstance (VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:39)
VContainer.Internal.Registration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:44)
VContainer.Container+<>c__DisplayClass4_0.<.ctor>b__1 () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:132)
System.Lazy`1[T].CreateValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].LazyInitValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].get_Value () (at <9577ac7a62ef43179789031239ba8798>:0)
VContainer.Container.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:152)
VContainer.ScopedContainer.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:68)
VContainer.ScopedContainer.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:74)
VContainer.ScopedContainer.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:55)
VContainer.IObjectResolverExtensions.ResolveOrParameter (VContainer.IObjectResolver resolver, System.Type parameterType, System.String parameterName, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/IObjectResolverExtensions.cs:30)
VContainer.Internal.ReflectionInjector.CreateInstance (VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:39)
VContainer.Internal.Registration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:44)
VContainer.ScopedContainer+<>c__DisplayClass10_0.<.ctor>b__1 () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:48)
System.Lazy`1[T].CreateValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].LazyInitValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].get_Value () (at <9577ac7a62ef43179789031239ba8798>:0)
VContainer.ScopedContainer.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:78)
VContainer.ScopedContainer.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:55)
VContainer.IObjectResolverExtensions.ResolveOrParameter (VContainer.IObjectResolver resolver, System.Type parameterType, System.String parameterName, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/IObjectResolverExtensions.cs:30)
VContainer.Internal.ReflectionInjector.InjectMethods (System.Object obj, VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:99)
VContainer.Internal.ReflectionInjector.Inject (System.Object instance, VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:23)
VContainer.Internal.ReflectionInjector.CreateInstance (VContainer.IObjectResolver resolver, System.Collections.Generic.IReadOnlyList`1[T] parameters) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/ReflectionInjector.cs:50)
VContainer.Internal.Registration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:44)
VContainer.ScopedContainer+<>c__DisplayClass10_0.<.ctor>b__1 () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:48)
System.Lazy`1[T].CreateValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].LazyInitValue () (at <9577ac7a62ef43179789031239ba8798>:0)
System.Lazy`1[T].get_Value () (at <9577ac7a62ef43179789031239ba8798>:0)
VContainer.ScopedContainer.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:78)
VContainer.Internal.CollectionRegistration.SpawnInstance (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Internal/Registration.cs:92)
VContainer.ScopedContainer.Resolve (VContainer.IRegistration registration) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:63)
VContainer.ScopedContainer.Resolve (System.Type type) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Container.cs:55)
VContainer.IObjectResolverExtensions.Resolve[T] (VContainer.IObjectResolver resolver) (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/IObjectResolverExtensions.cs:8)
VContainer.Unity.LifetimeScope.ActivateEntryPoints () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Unity/LifetimeScope.cs:264)
VContainer.Unity.LifetimeScope.Build () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Unity/LifetimeScope.cs:162)
VContainer.Unity.LifetimeScope.Awake () (at Library/PackageCache/jp.hadashikick.vcontainer@8fd4963749/Runtime/Unity/LifetimeScope.cs:122)
```

Is it because of that inheritance chain with generics? How to avoid that error if I still want to use that generic base classes?

**Comment by hadashiA** [comment] 2020-11-25 14:18
@dre0dru  Thanks for the bug report.

`IndexOutOfRangeException` is a strange error.

I tried the below, but couldn't get a reproduction 🤔 
Would you please share the Register code etc.?

--

```csharp
[CreateAssetMenu(fileName = "SampleScriptableObject", menuName = "Playground/Create SampleScriptableObject")]
public class SampleScriptableObject : ScriptableObject
{
}
```

```csharp
public interface ISomeInterface<T>
{
}

public abstract class Base<T>: ISomeInterface<T>
{
    public void Log()
    {
        UnityEngine.Debug.Log($"!!!!! {GetType()} take {typeof(T)} as a parameter");
    }
}

public class ActualGenericClass
{
}

public abstract class AnotherBase<T>: Base<T>
{
    readonly SampleScriptableObject dep;

    protected AnotherBase(SampleScriptableObject dep)
    {
        this.dep = dep;
    }
}

public class ActualClass: AnotherBase<ActualGenericClass>
{
    public ActualClass(SampleScriptableObject dep) : base(dep)
    {
    }
}

// ---

public class SampleEntryPoint : IInitializable
{
    readonly ActualClass actualClass;

    public SampleEntryPoint(ActualClass actualClass)
    {
        this.actualClass = actualClass;
    }

    void IInitializable.Initialize()
    {
        actualClass.Log();
    }
}

public class SampleLifetimeScope : LifetimeScope
{
    [SerializeField]
    SampleScriptableObject sampleScriptableObject;

    protected override void Configure(IContainerBuilder builder)
    {
        builder.RegisterInstance(sampleScriptableObject);
        builder.Register<ActualClass>(Lifetime.Singleton);
        builder.RegisterEntryPoint<SampleEntryPoint>(Lifetime.Singleton);
    }
}
```

**Comment by dre0dru** [comment] 2020-11-25 15:52
Hello! This is package to reproduce the bug. It is just butchered code from actual project. Open `LoginScene` and press play.
The inheritance hierarchy starts from `IStorage<T>` and ends with `AuthenticationStorage`.
Storage and `ScriptableObject` are registered in `RootScriptableObjectsInstaller`. Which is itself referenced by `RootLifeTimeScope` in `VContainerSettings`.

I tried to keep minimal code, but there is still bunch of classes, hope this won't be too confusing.
I am using VContainer 1.1.1. No other dependencies required to reproduce it.

[repro.zip](https://github.com/hadashiA/VContainer/files/5597732/repro.zip)

**Comment by hadashiA** [comment] 2020-11-26 04:47
@dre0dru  Thank you for the reproduced code!
This error was due to a mistake in my implementation of Simple ArrayPool...

In # 61, I have added a unit test that reproduces the problem and confirmed that it will be fixed.
I have also confirmed that this fix eliminates the error in the repro.zip project as well.

**Comment by hadashiA** [comment] 2020-11-26 04:58
I just released this fix.
https://github.com/hadashiA/VContainer/releases/tag/1.2.1

**Closed** 2020-11-26 18:38 UTC
