### ISSUE TITLE
[Bug] High level stripping removes ContainerLocal<T> ctor

### ISSUE THREAD

**Issue by vangogih** [hadashiA/VContainer#362] opened 2022-03-31 08:59 UTC
Hi @hadashiA,

Compilation params:
- Strip Engine code -> false or true (doesn't matter)
- Managed stripping level -> High

In runtime I've got an exception:

```
MissingMethodException: Constructor on type 
'VContainer.Internal.ContainerLocal`1[[System.Collections.Generic.IReadOnlyList`1[[VContainer.Unity.IInitializable, VContainer, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]' not found.
```

This problem can only be fixed by using link.xml file by saving the entire VContainer assembly or the `ContainerLocal<T>` class:
```
<linker>
  <assembly fullname="VContainer" preserve="all"/>
</linker>
```
OR
```
<linker>
  <assembly fullname="VContainer">
    <type fullname="VContainer.Internal.ContainerLocal`1" preserve="all"/>
  <assembly/>
</linker>
```
OR
```
<linker>
  <assembly fullname="VContainer">
    <type fullname="VContainer.Internal.ContainerLocal`1" preserve="methods"/>
  <assembly/>
</linker>
```
Or you need to add the `UnityEngine.Scripting.PreserveAttribute` for `ContainerLocal<T>` ctor or class.
The attribute or data to xml must be added for all classes which will be injected internally in future.

More info about Data Formats for .NET Linker: https://github.com/dotnet/linker/blob/main/docs/data-formats.md

**Comment by hadashiA** [comment] 2022-04-09 07:15
Thanks for the suggestion.

As for the stripping problem inside the library, I would like to do that, since it can all be controlled by attaching an attribute to the constructor.
( Fixed in #354 )

- Seems simpler not to depends on link.xml
- I think stripping should work.

However, I think your suggestion of a mechanism to not release the issue is excellent.
I would like to consider ways to prevent this with CI.

**Closed** 2022-04-09 07:21 UTC
